
package Ejercicio5_6;

public class A {
    
 /*   public void metodoA() { 
        sentencia_a1; 
        sentencia_a2;
        try { 
            sentencia_a3 
            sentencia_a4 
        } catch (MioException e){ 
            sentencia_a6
         }
        sentencia_a5 } 
       }

    a)   ¿Qué  sentencias  y  en  qué  orden  se  ejecutan  si  se  produce  la  excepción MioException?
     a1, a2, a3, a4, a6
    
    b)  ¿Qué  sentencias  y  en  qué  orden  se  ejecutan  si  no  se  produce  la  excepción MioException?
     a1, a2, a3, a4, a5
    
    class B {
     void metodoB() { 
        sentencia_b1 
        try { 
          sentencia_b2 
        } catch (MioException e){
          sentencia_b3 
        } finally{
            sentencia_b4 } }

     a)   ¿Qué  sentencias  y  en  qué  orden  se  ejecutan  si  se  produce  la  excepción MioException?

      - b1, b2, b3, b4
 
     b)  ¿Qué  sentencias  y  en  qué  orden  se  ejecutan  si  no  se  produce  la  excepción MioException?
      
      - b1, b2, b4

*/
}
